### ISSUE TITLE
Set for thread and post separately?

### ISSUE THREAD

**Issue by Eldenroot** [OUGC-Network/OUGC-Force-Post-Captcha#1]
Ability to have different settings for post a thread / post a post.

**Comment by Sama34** [comment]
So you want to enable it for posts in specific forums and forum threads in another forums?

That isn't a planed feature, as I think you can use xThreads forum specific settings to achieve it. If it isn't possible with xThreads then I might add it.

**Comment by Eldenroot** [comment]
OK, thx!
